// Zweitagesseminar "Mentale Stärke, Achtsamkeit und Entschleunigung im Arbeitsalltag"
const path = require("path");
const { createDeck } = require("./layouts");

const S = [
  // ───────────── ERÖFFNUNG ─────────────
  { t: "cover", kicker: "ZWEITAGESSEMINAR", title: "Mentale Stärke, Achtsamkeit und Entschleunigung im Arbeitsalltag", size: 32,
    sub: "Gelassener, klarer und ressourcenschonender arbeiten – ohne an Leistungsfähigkeit zu verlieren",
    meta: "Landkreis Osterholz  ·  Bildungsstätte Bredbeck", icon: "FaLeaf",
    notes: "Begrüßung, eigene Vorstellung, Organisatorisches (Räume, Pausen, Verpflegung, Wald-Exkursion an Tag 2)." },
  { t: "grid", title: "Herzlich willkommen in Bredbeck", lead: "Zwei Tage, um den Blick vom Schreibtisch zu heben und bewusst bei sich anzukommen.", leadItalic: true,
    items: [["FaChair", "Raum", "Ein geschützter Rahmen fern vom Tagesgeschäft – für Austausch und neue Impulse."],
      ["FaTree", "Natur", "Der Wald rund um Bredbeck wird an Tag 2 selbst zum Seminarraum."],
      ["FaHourglassHalf", "Zeit", "Zeit für Reflexion, Übungen und das, was im Alltag oft zu kurz kommt."]] },
  { t: "iconList", title: "Unsere Lernziele", sub: "Nach dem Seminar können Sie …",
    items: [["FaSearch", "Belastungen erkennen", "Belastungsfaktoren im Arbeitsalltag bewusster erkennen und einordnen."],
      ["FaShieldAlt", "Widerstandskraft stärken", "Ihre mentale Widerstandskraft gezielt stärken."],
      ["FaSpa", "Achtsamkeit anwenden", "Achtsamkeits- und Entspannungsübungen sicher im Alltag anwenden."],
      ["FaBalanceScale", "Gelassener handeln", "Bewusster mit Gedanken, Emotionen und Reaktionen umgehen."],
      ["FaTree", "Natur nutzen", "Die heilsame Wirkung von Natur, Ruhe und Entschleunigung für sich nutzen."]] },
  { t: "compare", title: "Die zwei Tage im Überblick",
    left: { icon: "FaBrain", h: "Tag 1: Mentale Gesundheit & Mindset", items: ["Mentale Gesundheit im Arbeitskontext", "Stress verstehen: innere und äußere Faktoren", "Resilienz und mentale Stärke", "Gedanken und Bewertungen wahrnehmen", "Selbstreflexion und Ressourcen"] },
    right: { icon: "FaTree", h: "Tag 2: Achtsamkeit & Waldbaden", items: ["Achtsamkeit als Haltung und Methode", "Atem-, Wahrnehmungs- und Kurzentspannung", "Entschleunigung: kleine Pausen, große Wirkung", "Geführte Waldbaden-Exkursion", "Transfer in den Berufsalltag"] } },
  { t: "timeline", title: "Ablauf Tag 1",
    rows: [["09:00", "Ankommen & Kennenlernen"], ["09:45", "Mentale Gesundheit im Arbeitskontext"], ["10:45", "Kaffeepause", true], ["11:00", "Stress verstehen"],
      ["12:30", "Mittagspause", true], ["13:30", "Resilienz & mentale Stärke"], ["15:00", "Pause", true], ["15:15", "Gedanken & Bewertungen"], ["16:30", "Tagesabschluss"]],
    side: { icon: "FaBrain", h: "Motto des Tages", d: "Verstehen, was uns belastet – und entdecken, was uns stark macht." },
    notes: "Zeiten sind ein Vorschlag und können an die Gruppe angepasst werden." },
  { t: "grid", title: "Unsere Vereinbarungen",
    items: [["FaLock", "Vertraulichkeit", "Was hier persönlich geteilt wird, bleibt im Raum."],
      ["FaHandshake", "Freiwilligkeit", "Alle Übungen sind Angebote. Sie entscheiden, was Sie teilen."],
      ["FaBellSlash", "Handy auf lautlos", "Wir schenken uns ungeteilte Aufmerksamkeit – Pausen gibt es regelmäßig."],
      ["FaHeart", "Wohlwollen", "Wir hören einander zu, ohne zu bewerten. Jede Erfahrung zählt."]] },
  { t: "steps", title: "Kennenlernen: Mein Kraftort", pill: "ÜBUNG · 30 MIN",
    items: [["Name & Arbeitsbereich", "Wer sind Sie, und wo arbeiten Sie im Landkreis?"],
      ["Mein Kraftort", "Ein Ort, an dem Sie auftanken – ein Platz im Garten, am Wasser, im Moor …"],
      ["Was mir dort guttut", "Was genau erleben Sie dort? Was spüren, hören, sehen Sie?"],
      ["Mein Anliegen", "Was möchte ich aus diesen zwei Tagen mitnehmen?"]],
    side: { icon: "FaMapSigns", h: "Hinweis", d: "Die Anliegen sammeln wir auf Moderationskarten an der Pinnwand. Am Ende von Tag 2 schauen wir, was sich erfüllt hat." },
    notes: "Runde im Stuhlkreis, ca. 2 Minuten pro Person. Anliegen auf Karten notieren lassen und an die Pinnwand heften." },
  { t: "scale", title: "Energie-Barometer", pill: "ÜBUNG · 5 MIN", q: "Wie voll ist Ihr Energietank gerade? Setzen Sie einen Klebepunkt.",
    left: "1 = völlig leer", right: "10 = voller Energie", extra: "Und im Durchschnitt der letzten drei Monate? Setzen Sie einen zweiten Punkt in einer anderen Farbe.",
    notes: "Flipchart mit Skala vorbereiten. Das Bild der Gruppe kurz wertfrei spiegeln. Am Ende von Tag 2 wiederholen." },

  // ───────────── BLOCK 1: MENTALE GESUNDHEIT ─────────────
  { t: "section", n: "01", title: "Mentale Gesundheit", sub: "Was sie im Arbeitskontext bedeutet – und warum sie uns alle angeht.", icon: "FaHeartbeat" },
  { t: "quote", text: "Mentale Gesundheit ist mehr als die Abwesenheit von Krankheit.", size: 30,
    src: "Sinngemäß nach der Weltgesundheitsorganisation (WHO)",
    sub: "Sie ist ein Zustand des Wohlbefindens, in dem wir unsere Fähigkeiten nutzen, mit Belastungen umgehen, produktiv arbeiten und etwas zur Gemeinschaft beitragen können." },
  { t: "grid", title: "Salutogenese: Was hält uns gesund?", sub: "Das Kohärenzgefühl nach Aaron Antonovsky",
    items: [["FaSearch", "Verstehbarkeit", "Ich kann einordnen, was um mich herum passiert. Die Dinge ergeben ein Bild."],
      ["FaTools", "Handhabbarkeit", "Ich habe Ressourcen, um Anforderungen zu bewältigen – eigene oder mit Unterstützung."],
      ["FaCompass", "Sinnhaftigkeit", "Es lohnt sich, mich zu engagieren. Meine Arbeit ergibt für mich Sinn."]],
    notes: "Perspektivwechsel: Nicht nur fragen, was krank macht, sondern was gesund hält. Gesundheit als Kontinuum, nicht als Entweder-oder." },
  { t: "compare", title: "Anforderungen und Ressourcen", sub: "Die Balance entscheidet – nicht die Belastung allein",
    left: { icon: "FaWeightHanging", h: "Anforderungen", items: ["Arbeitsmenge und Zeitdruck", "Verantwortung und Entscheidungen", "Schwierige Gespräche", "Ständige Veränderungen"] },
    right: { icon: "FaBatteryFull", h: "Ressourcen", items: ["Handlungsspielraum", "Unterstützung im Team", "Anerkennung und Sinn", "Eigene Erfahrung und Kompetenz"] },
    foot: "Wenn Anforderungen dauerhaft die Ressourcen übersteigen, entsteht Stress. Die gute Nachricht: An beiden Seiten lässt sich arbeiten.",
    notes: "Angelehnt an das Job-Demands-Resources-Modell (Bakker & Demerouti)." },
  { t: "grid", title: "Arbeitsalltag in der Kreisverwaltung", lead: "Was kennen Sie davon?",
    items: [["FaUserShield", "Verantwortung", "Entscheidungen mit Wirkung auf Bürgerinnen, Bürger und Kolleg:innen."],
      ["FaInbox", "Infoflut", "E-Mails, Vorgänge, Vorschriften – und alles gleichzeitig."],
      ["FaRandom", "Wechselnde Anforderungen", "Neue Gesetze, Zuständigkeiten und Prioritäten."],
      ["FaComments", "Anspruchsvolles Miteinander", "Bürgerkontakt, Schnittstellen, unterschiedliche Erwartungen."],
      ["FaLaptop", "Digitalisierung", "Neue Programme und Abläufe, die eingeübt werden wollen."],
      ["FaUserClock", "Vertretungen", "Fehlende Stellen und Urlaubszeiten verdichten die Arbeit."]],
    notes: "Kurz per Handzeichen abfragen, was am meisten zutrifft. Noch nicht vertiefen – wird im Stress-Block aufgegriffen." },
  { t: "compare", title: "Mit 50+ im Beruf: Stärken nutzen",
    left: { icon: "FaGem", h: "Was mit den Jahren wächst", items: ["Erfahrungswissen und Überblick", "Urteilsvermögen und Gelassenheit", "Tragfähige Netzwerke", "Wissen um die eigenen Grenzen"] },
    right: { icon: "FaHandHoldingHeart", h: "Worauf wir mehr achten dürfen", items: ["Erholung braucht oft mehr Zeit", "Schlaf wird störanfälliger", "Bewegung wird wichtiger", "Pausen bewusst einplanen"] },
    notes: "Wertschätzend moderieren: Alter nicht als Defizit, sondern als Ressource. Die rechte Seite als Einladung zur Selbstfürsorge." },
  { t: "reflection", title: "Meine Arbeitssituation", pill: "REFLEXION · 10 MIN",
    qs: ["Was gibt mir in meiner Arbeit Kraft und Sinn?", "Was kostet mich derzeit besonders viel Energie?", "Wo habe ich Gestaltungsspielraum – auch einen kleinen?", "Was hat sich in den letzten Jahren für mich verändert?"],
    notes: "Einzelarbeit, danach Austausch in Zweiergruppen (5 Min)." },
  { t: "steps", title: "Meine Energiebilanz", pill: "ÜBUNG · 15 MIN",
    items: [["Blatt teilen", "Zeichnen Sie eine Linie in die Mitte: links Räuber, rechts Spender."],
      ["Sammeln", "Notieren Sie je 5 Dinge aus Beruf und Privatleben."],
      ["Gewichten", "Markieren Sie die drei stärksten Räuber und Spender."],
      ["Eine Stellschraube", "Welchen Räuber können Sie verkleinern, welchen Spender vergrößern?"]],
    side: { icon: "FaBalanceScale", h: "Leitfrage", d: "Was wäre eine kleine Veränderung, die meine Bilanz schon nächste Woche verbessert?" } },
  { t: "grid", title: "Tipp: Frühwarnsignale erkennen", pill: "ALLTAGSTIPP",
    items: [["FaHeartbeat", "Körper", "Verspannungen, Kopfschmerzen, Magen-Darm-Beschwerden."],
      ["FaBrain", "Gedanken", "Grübeln, Konzentrationsprobleme, „Ich schaffe das nicht“."],
      ["FaTheaterMasks", "Gefühle", "Gereiztheit, Unruhe, Niedergeschlagenheit."],
      ["FaRunning", "Verhalten", "Hektik, mehr Kaffee, weniger Pausen, Rückzug."],
      ["FaBed", "Schlaf", "Schlecht einschlafen, nachts aufwachen und grübeln."],
      ["FaUsers", "Kontakte", "Weniger Lust auf Menschen, Hobbys, Unternehmungen."]],
    notes: "Frage an die Gruppe: Was ist Ihr persönliches erstes Warnsignal? Wer sein Signal kennt, kann früher gegensteuern." },

  // ───────────── BLOCK 2: STRESS VERSTEHEN ─────────────
  { t: "section", n: "02", title: "Stress verstehen", sub: "Innere und äußere Belastungsfaktoren erkennen und einordnen.", icon: "FaBolt" },
  { t: "compare", title: "Was ist Stress?", sub: "Nach Hans Selye: Stress ist nicht per se schlecht",
    left: { icon: "FaFire", h: "Eustress", items: ["Aktiviert und motiviert", "Zeitlich begrenzt", "Gefühl von Herausforderung", "Macht auch Freude"] },
    right: { icon: "FaExclamationTriangle", h: "Distress", items: ["Überfordert und lähmt", "Dauerhaft, ohne Erholung", "Gefühl von Bedrohung", "Macht auf Dauer krank"] },
    foot: "Entscheidend ist der Wechsel: Anspannung braucht Entspannung – wie Ein- und Ausatmen." },
  { t: "grid", title: "Die Stressreaktion im Körper", sub: "Ein uraltes Programm für Kampf oder Flucht", cols: 5,
    items: [["1", "Wahrnehmen", "Das Gehirn meldet: Gefahr oder Anforderung!"],
      ["2", "Alarm", "Stresshormone wie Adrenalin und Cortisol werden ausgeschüttet."],
      ["3", "Energie", "Puls, Blutdruck und Muskelspannung steigen."],
      ["4", "Tunnelblick", "Aufmerksamkeit verengt sich, kreatives Denken sinkt."],
      ["5", "Erholung", "Nach der Gefahr fährt der Körper wieder herunter – wenn wir ihn lassen."]],
    notes: "Heute ist die 'Gefahr' oft eine volle Mailbox. Der Körper reagiert gleich, doch die Energie wird nicht durch Bewegung abgebaut." },
  { t: "letters", title: "Die Stress-Ampel nach Gert Kaluza", hi: 1,
    items: [["1", "Stressoren", "Was setzt mich unter Druck? Zeitdruck, Konflikte, Lärm, Unterbrechungen."],
      ["2", "Stressverstärker", "Was mache ich daraus? Eigene Ansprüche, Erwartungen, innere Antreiber."],
      ["3", "Stressreaktion", "Was passiert mit mir? Körper, Gefühle, Gedanken, Verhalten."]],
    foot: "Ich gerate in Stress, weil … (1), weil ich … (2), und dann … (3)." },
  { t: "grid", title: "Äußere Belastungsfaktoren",
    items: [["FaStopwatch", "Zeit", "Fristen, Termindichte, zu viele Aufgaben gleichzeitig."],
      ["FaBell", "Unterbrechungen", "Telefon, E-Mails, „Hast du mal kurz …?“"],
      ["FaUsers", "Soziales", "Konflikte, schwierige Gespräche, fehlende Wertschätzung."],
      ["FaRandom", "Veränderung", "Umstrukturierung, neue Software, neue Vorgesetzte."],
      ["FaVolumeUp", "Umgebung", "Lärm, Großraumbüro, schlechte Luft, Licht."],
      ["FaHome", "Privates", "Pflege von Angehörigen, Gesundheit, Familie."]] },
  { t: "grid", title: "Innere Stressverstärker", sub: "Persönliche Antreiber nach Gert Kaluza", cols: 5,
    items: [["FaStar", "Sei perfekt!", "„Fehler darf ich mir nicht erlauben.“"],
      ["FaSmile", "Sei beliebt!", "„Ich will es allen recht machen.“"],
      ["FaShieldAlt", "Sei stark!", "„Ich schaffe das allein.“"],
      ["FaLock", "Sei vorsichtig!", "„Ich muss alles unter Kontrolle haben.“"],
      ["FaWeightHanging", "Ich kann nicht!", "„Das ist mir alles zu viel.“"]],
    notes: "Antreiber haben meist eine gute Absicht und sind oft Teil unseres Erfolgs. Problematisch wird es, wenn sie absolut werden." },
  { t: "steps", title: "Meine Stressverstärker", pill: "ÜBUNG · 15 MIN",
    items: [["Einschätzen", "Bewerten Sie jeden der fünf Antreiber von 1 (trifft nicht zu) bis 5 (trifft voll zu)."],
      ["Erkennen", "Welcher Antreiber ist bei Ihnen am stärksten? In welchen Situationen zeigt er sich?"],
      ["Würdigen", "Wobei hat Ihnen dieser Antreiber schon geholfen?"],
      ["Erlauber formulieren", "Finden Sie einen entlastenden Satz: „Gut ist gut genug.“"]],
    side: { icon: "FaFeather", h: "Beispiele für Erlauber", d: "„Ich darf Fehler machen.“\n„Ich darf Nein sagen.“\n„Ich darf um Hilfe bitten.“\n„Ich darf Pause machen.“" } },
  { t: "letters", title: "Stress entsteht durch Bewertung", sub: "Transaktionales Stressmodell nach Richard Lazarus", hi: 1,
    items: [["1", "Erste Bewertung", "Ist die Situation für mich positiv, irrelevant oder bedrohlich?"],
      ["2", "Zweite Bewertung", "Habe ich die Mittel, um damit umzugehen?"],
      ["3", "Bewältigung", "Ich handle, suche Unterstützung oder verändere meine Sicht."]],
    foot: "Dieselbe Situation kann für zwei Menschen völlig unterschiedlichen Stress bedeuten." },
  { t: "grid", title: "Drei Wege der Stressbewältigung", sub: "Nach Gert Kaluza",
    items: [["FaTools", "Instrumentell", "Die Situation verändern: planen, delegieren, Nein sagen, Probleme lösen."],
      ["FaBrain", "Mental", "Die Bewertung verändern: Ansprüche prüfen, Gedanken umdeuten, annehmen."],
      ["FaSpa", "Regenerativ", "Die Reaktion abfedern: Entspannung, Bewegung, Schlaf, soziale Kontakte."]] },
  { t: "steps", title: "Meine Stress-Landkarte", pill: "PARTNERÜBUNG · 20 MIN",
    items: [["Situation wählen", "Wählen Sie eine typische Stresssituation aus Ihrem Arbeitsalltag."],
      ["Ampel anwenden", "Was ist der Stressor? Was ist mein Verstärker? Wie reagiere ich?"],
      ["Wege sammeln", "Suchen Sie gemeinsam je eine Idee für alle drei Bewältigungswege."],
      ["Rollentausch", "Nach 10 Minuten wechseln Sie die Rollen."]],
    side: { icon: "FaUserFriends", h: "Als Zuhörende", d: "Zuhören, nachfragen, Ideen anbieten – nicht bewerten und keine Ratschläge aufdrängen." } },
  { t: "steps", title: "Tipp: Die schnelle Stressbremse", pill: "ÜBUNG · 2 MIN", lead: "Der „physiologische Seufzer“ – zweimal ein, einmal lang aus:",
    items: [["Tief einatmen", "Durch die Nase einatmen, bis die Lunge fast gefüllt ist."],
      ["Nachatmen", "Noch einmal kurz durch die Nase nachschnuppern."],
      ["Lang ausatmen", "Langsam und vollständig durch den Mund ausatmen."],
      ["Wiederholen", "Zwei bis drei Mal – und spüren, wie der Körper ruhiger wird."]],
    side: { icon: "FaWind", h: "Warum es wirkt", d: "Eine verlängerte Ausatmung aktiviert den Parasympathikus – das körpereigene Bremssystem." } },
  { t: "steps", title: "Progressive Muskelentspannung", pill: "ÜBUNG · 15 MIN", sub: "Kurzform nach Edmund Jacobson",
    items: [["Hände & Arme", "Fäuste ballen, Arme anspannen, 5 Sek. halten – loslassen."],
      ["Gesicht", "Stirn runzeln, Augen und Lippen zusammenpressen – loslassen."],
      ["Schultern & Nacken", "Schultern zu den Ohren ziehen – halten – fallen lassen."],
      ["Bauch & Rücken", "Bauch anspannen, Schulterblätter zusammen – loslassen."],
      ["Beine & Füße", "Zehen anziehen, Beine strecken – loslassen."]],
    side: { icon: "FaSpa", h: "Hinweis", d: "Nur so stark anspannen, dass es angenehm bleibt. Bei Beschwerden die Region auslassen." },
    notes: "Im Sitzen anleiten, ruhige Stimme, Pausen zum Nachspüren großzügig lassen." },

  // ───────────── BLOCK 3: RESILIENZ ─────────────
  { t: "section", n: "03", title: "Resilienz und mentale Stärke", sub: "Die innere Widerstandskraft im beruflichen Alltag stärken.", icon: "FaShieldAlt" },
  { t: "quote", text: "Resilienz heißt nicht, nie zu fallen – sondern immer wieder aufzustehen.", size: 30,
    src: "Resilienz = psychische Widerstandskraft", sub: "Wie ein Bambus im Sturm: Er biegt sich, aber er bricht nicht. Resilienz ist keine feste Eigenschaft, sondern lässt sich ein Leben lang stärken." },
  { t: "grid", title: "Die sieben Säulen der Resilienz", cols: 4, vertical: false,
    items: [["1", "Akzeptanz", "Annehmen, was sich nicht ändern lässt."],
      ["2", "Optimismus", "Vertrauen, dass schwere Zeiten vorübergehen."],
      ["3", "Selbstwirksamkeit", "Überzeugung, etwas bewirken zu können."],
      ["4", "Verantwortung", "Die eigene Rolle aktiv gestalten."],
      ["5", "Netzwerk", "Beziehungen pflegen, Hilfe annehmen."],
      ["6", "Lösungsfokus", "Nach vorne schauen statt grübeln."],
      ["7", "Zukunft planen", "Ziele setzen und gestalten."]],
    notes: "Modell in Anlehnung an Reivich & Shatté bzw. die deutschsprachige Resilienzliteratur. Säulen sind trainierbar." },
  { t: "steps", title: "Mein Resilienz-Profil", pill: "ÜBUNG · 15 MIN",
    items: [["Einschätzen", "Bewerten Sie jede der sieben Säulen von 1 bis 10."],
      ["Visualisieren", "Tragen Sie die Werte in das Netzdiagramm im Arbeitsblatt ein."],
      ["Stärke benennen", "Welche Säule ist Ihre stärkste? Wie hat sie Ihnen schon geholfen?"],
      ["Wachstum wählen", "Welche Säule möchten Sie um einen Punkt stärken – und wie?"]],
    side: { icon: "FaChartPie", h: "Wichtig", d: "Es gibt kein richtiges Profil. Jede Säule kann eine andere stützen." } },
  { t: "table", title: "Statisches und dynamisches Selbstbild", sub: "Mindset nach Carol Dweck", heads: ["Fixed Mindset", "Growth Mindset"],
    rows: [["Herausforderungen", "werden vermieden", "werden angenommen"], ["Hindernisse", "führen zum Aufgeben", "fördern Ausdauer"],
      ["Anstrengung", "gilt als sinnlos", "ist der Weg zum Können"], ["Kritik", "wird abgewehrt", "wird als Lernchance genutzt"], ["Veränderung", "wirkt bedrohlich", "weckt Neugier"]] },
  { t: "grid", title: "Neuroplastizität: Lernen ein Leben lang", lead: "Unser Gehirn bleibt in jedem Alter veränderbar. Was wir wiederholen, wird stärker.", leadItalic: true,
    items: [["FaShoePrints", "Trampelpfad", "Neue Denkweisen fühlen sich anfangs mühsam an – wie ein Weg durch hohes Gras."],
      ["FaRedo", "Wiederholung", "Jede Wiederholung stärkt die Verbindung. Aus dem Pfad wird ein Weg."],
      ["FaRoad", "Gewohnheit", "Gut trainierte Muster laufen automatisch ab. Das gilt auch für neue."]] },
  { t: "iconList", title: "Selbstwirksamkeit", sub: "Nach Albert Bandura: „Ich kann das schaffen.“",
    items: [["FaTrophy", "Eigene Erfolge", "Die stärkste Quelle: selbst etwas gemeistert haben."],
      ["FaUserFriends", "Vorbilder", "Sehen, wie Menschen wie ich es schaffen."],
      ["FaComments", "Ermutigung", "Zuspruch von anderen – und von mir selbst."],
      ["FaHeart", "Körpergefühl", "Anspannung als Energie deuten statt als Gefahr."]],
    side: { h: "Alltagstipp", d: "Große Aufgaben in kleine Schritte zerlegen. Jeder erreichte Schritt ist ein Mini-Erfolg und stärkt das Gefühl: Ich bewirke etwas." } },
  { t: "steps", title: "Meine Lebenslinie", pill: "ÜBUNG · 20 MIN",
    items: [["Linie zeichnen", "Zeichnen Sie Ihr Berufsleben als Linie mit Höhen und Tiefen."],
      ["Tiefpunkte markieren", "Wo gab es schwierige Phasen, Umbrüche oder Krisen?"],
      ["Wendepunkte finden", "Was hat Ihnen geholfen, wieder nach oben zu kommen?"],
      ["Stärken ableiten", "Welche Fähigkeiten haben Sie dabei gezeigt? Notieren Sie drei."]],
    side: { icon: "FaChartLine", h: "Erkenntnis", d: "Sie haben schon viele Stürme überstanden. Diese Erfahrung ist Ihr größtes Kapital." },
    notes: "Gerade für Teilnehmende 50+ sehr ergiebig. Achtsam begleiten: Nur teilen, was man teilen möchte." },
  { t: "steps", title: "Das Ressourcen-Interview", pill: "PARTNERÜBUNG · 20 MIN",
    items: [["Erzählen", "A erzählt von einer beruflichen Situation, die gut gemeistert wurde."],
      ["Nachfragen", "B fragt: Was genau hast du getan? Was hat dir geholfen?"],
      ["Spiegeln", "B benennt die Stärken, die er oder sie gehört hat."],
      ["Wechseln", "Nach 10 Minuten tauschen Sie die Rollen."]],
    side: { icon: "FaGift", h: "Hilfreiche Fragen", d: "„Wie hast du das geschafft?“\n„Was sagt das über dich aus?“\n„Wer oder was hat dich unterstützt?“" } },
  { t: "circles", title: "Mein Einflussbereich", inner: "Kann ich\nbeeinflussen", outer: "Liegt nicht in meiner Hand",
    inH: "In meiner Hand", inList: ["Meine Vorbereitung und Planung", "Meine Reaktion und Haltung", "Wen ich um Unterstützung bitte"],
    outH: "Nicht in meiner Hand", outList: ["Gesetzesänderungen, Politik", "Das Verhalten anderer", "Die Vergangenheit"],
    notes: "Nach Stephen Covey. Energie fließt dorthin, wo die Aufmerksamkeit ist." },
  { t: "steps", title: "Sorgen sortieren", pill: "ÜBUNG · 10 MIN",
    items: [["Zwei Kreise zeichnen", "Einen großen Kreis auf Ihr Blatt, darin einen kleinen."],
      ["Sorgen sammeln", "Notieren Sie alles, was Sie gerade beruflich beschäftigt."],
      ["Einsortieren", "Was können Sie beeinflussen? Innen. Alles andere: außen."],
      ["Einen Schritt wählen", "Nehmen Sie sich für den inneren Kreis eine konkrete Handlung vor."]],
    side: { icon: "FaHandPaper", h: "Für den äußeren Kreis", d: "Hier hilft Akzeptanz: „Das kann ich nicht ändern. Ich entscheide, wie viel Raum ich ihm gebe.“" } },
  { t: "grid", title: "Rückschläge meistern: Die 3 P", sub: "Nach Martin Seligman",
    items: [["FaUser", "Persönlich", "Falle: „Es liegt nur an mir.“\nGegenfrage: Welche Umstände haben auch mitgespielt?"],
      ["FaInfinity", "Permanent", "Falle: „Das wird immer so sein.“\nGegenfrage: Was kann beim nächsten Mal anders sein?"],
      ["FaGlobeEurope", "Pervasiv", "Falle: „Alles geht schief.“\nGegenfrage: Welche Lebensbereiche laufen gerade gut?"]] },

  // ───────────── BLOCK 4: GEDANKEN ─────────────
  { t: "section", n: "04", title: "Gedanken und Bewertungen", sub: "Einstellungen und innere Bewertungen bewusst wahrnehmen.", icon: "FaLightbulb" },
  { t: "quote", text: "Nicht die Dinge selbst beunruhigen die Menschen, sondern ihre Urteile über die Dinge.", size: 28,
    src: "Epiktet, griechischer Philosoph (ca. 50–138 n. Chr.)", sub: "Diese fast 2.000 Jahre alte Einsicht ist die Grundlage moderner kognitiver Methoden." },
  { t: "letters", title: "Das ABC-Modell nach Albert Ellis", hi: 1,
    items: [["A", "Auslöser", "Die Amtsleitung antwortet seit zwei Tagen nicht auf meine Mail."],
      ["B", "Bewertung", "„Sie ist bestimmt unzufrieden mit meiner Arbeit.“"],
      ["C", "Konsequenz", "Unruhe, Grübeln am Abend, schlechter Schlaf."]],
    foot: "Der Hebel liegt bei B: Den Auslöser können wir oft nicht ändern – unsere Bewertung schon." },
  { t: "steps", title: "Meine ABC-Analyse", pill: "ÜBUNG · 15 MIN",
    items: [["A – Situation", "Denken Sie an eine Situation der letzten Wochen, die Sie belastet hat."],
      ["B – Gedanken", "Was genau haben Sie in dem Moment gedacht? Möglichst wörtlich."],
      ["C – Folgen", "Welche Gefühle, Körperreaktionen und Handlungen folgten?"],
      ["D – Hinterfragen", "Ist der Gedanke wahr? Hilfreich? Gibt es eine andere Sicht?"],
      ["E – Neue Wirkung", "Wie fühlen Sie sich mit der neuen Sichtweise?"]],
    side: { icon: "FaPen", h: "Austausch", d: "Wer mag, teilt im Plenum seine neue Sichtweise (D) – ohne die Situation im Detail zu schildern." } },
  { t: "grid", title: "Typische Denkfallen",
    items: [["FaAdjust", "Schwarz-Weiß-Denken", "„Entweder perfekt oder gar nicht.“"],
      ["FaBomb", "Katastrophisieren", "„Wenn das schiefgeht, ist alles vorbei.“"],
      ["FaGlasses", "Gedankenlesen", "„Die denken bestimmt, ich bin zu alt dafür.“"],
      ["FaInfinity", "Verallgemeinern", "„Das klappt bei mir nie.“"],
      ["FaExclamationTriangle", "Muss-Sätze", "„Ich muss immer erreichbar sein.“"],
      ["FaUser", "Personalisieren", "„Die Stimmung im Team ist schlecht – meinetwegen.“"]],
    notes: "Nach Aaron T. Beck (kognitive Verzerrungen). Mit Humor moderieren: Wir alle kennen diese Fallen." },
  { t: "steps", title: "Denkfallen-Detektiv", pill: "ÜBUNG · 10 MIN",
    items: [["Sammeln", "Notieren Sie drei belastende Gedanken aus Ihrem Arbeitsalltag."],
      ["Zuordnen", "Welche Denkfalle steckt jeweils dahinter?"],
      ["Beweise prüfen", "Was spricht dafür, was dagegen? Was sind Fakten, was Vermutungen?"],
      ["Neu formulieren", "Formulieren Sie einen realistischeren, hilfreicheren Gedanken."]],
    side: { icon: "FaSearch", h: "Beispiel", d: "„Das klappt nie.“\n→ „Es hat diesmal nicht geklappt. Beim letzten Projekt lief es gut.“" } },
  { t: "grid", title: "Gedanken umdeuten: Reframing", pill: "ÜBUNG · 10 MIN", lead: "Wählen Sie einen belastenden Gedanken und stellen Sie sich drei Fragen:",
    items: [["FaQuestion", "Stimmt das wirklich?", "Welche Fakten sprechen dafür – welche dagegen?"],
      ["FaUserFriends", "Was würde ich einer Kollegin raten?", "Zu anderen sind wir oft viel freundlicher als zu uns selbst."],
      ["FaRegClock", "Wie wichtig ist das in einem Jahr?", "Abstand relativiert – und schafft Handlungsspielraum."]] },
  { t: "compare", title: "Innerer Kritiker und innerer Coach", pill: "ÜBUNG · 10 MIN",
    left: { h: "Innerer Kritiker", italic: true, items: ["„Das hättest du wissen müssen.“", "„Andere schaffen das mit links.“", "„Mit über 50 lernst du das nicht mehr.“"] },
    right: { h: "Innerer Coach", italic: true, items: ["„Das war schwierig. Was nimmst du mit?“", "„Du hast schon Schwereres geschafft.“", "„Schritt für Schritt – du hast Zeit.“"] },
    foot: "Übung: Schreiben Sie drei typische Sätze Ihres Kritikers auf und formulieren Sie jeweils eine Antwort Ihres Coaches. Tipp: Sprechen Sie mit sich selbst mit Ihrem Vornamen – das schafft Abstand." },
  { t: "arrows", title: "Tipp: Die Kraft des Wortes „noch“", pill: "ALLTAGSTIPP",
    rows: [["Ich kann das nicht.", "Ich kann das noch nicht."], ["Mit der neuen Software komme ich nicht klar.", "Ich lerne die Software gerade noch."], ["Das klappt bei mir nie.", "Das hat bisher noch nicht geklappt."]],
    foot: "Ein kleines Wort verwandelt ein Urteil in einen Prozess." },
  { t: "steps", title: "Abstand zu Gedanken gewinnen", pill: "ÜBUNG · 5 MIN", lead: "Gedanken sind Ereignisse im Kopf – keine Tatsachen.",
    items: [["Gedanken wählen", "Nehmen Sie einen belastenden Gedanken, z. B. „Ich schaffe das nicht.“"],
      ["Umformulieren", "Innerlich: „Ich habe den Gedanken, dass …“"],
      ["Noch mehr Abstand", "„Ich bemerke, dass ich den Gedanken habe …“"],
      ["Nachspüren", "Was verändert sich? Meist verliert der Gedanke etwas an Kraft."]],
    side: { icon: "FaCloud", h: "Bild dazu", d: "Gedanken sind wie Wolken am Himmel. Wir können sie beobachten, ohne ihnen hinterherzulaufen." },
    notes: "Technik der kognitiven Defusion aus der Akzeptanz- und Commitment-Therapie (ACT, Steven Hayes)." },
  { t: "reflection", title: "Tagesabschluss", pill: "REFLEXION · 20 MIN",
    qs: ["Was war heute für mich die wichtigste Erkenntnis?", "Welche Übung probiere ich heute Abend oder morgen früh aus?", "Mit welchem Gefühl gehe ich aus dem ersten Tag?"],
    notes: "Blitzlicht im Stuhlkreis: jede Person ein bis zwei Sätze. Ausblick auf Tag 2 und Hinweis auf wetterfeste Kleidung für den Wald." },
  { t: "big", title: "Tipp für den Abend: Drei gute Dinge", pill: "ALLTAGSTIPP", num: "3", label: "Dinge, jeden Abend", info: "Übung aus der Positiven Psychologie (Martin Seligman)",
    items: [["Aufschreiben", "Drei Dinge, die heute gut waren – auch kleine."], ["Warum?", "Notieren Sie, warum sie passiert sind und was Ihr Anteil war."], ["Dranbleiben", "Eine Woche lang täglich – dann Wirkung beobachten."]],
    notes: "Hausaufgabe für den Abend. Morgen früh kurz nachfragen." },

  // ───────────── TAG 2 ─────────────
  { t: "cover", kicker: "TAG 2", title: "Achtsamkeit, Entschleunigung und Waldbaden", size: 36,
    sub: "Guten Morgen! Heute steht das bewusste Erleben im Mittelpunkt.", meta: "Bildungsstätte Bredbeck  ·  Seminarraum und Wald", icon: "FaTree" },
  { t: "timeline", title: "Ablauf Tag 2",
    rows: [["09:00", "Ankommen & Check-in"], ["09:30", "Achtsamkeit"], ["10:45", "Kaffeepause", true], ["11:00", "Atem & Kurzentspannung"], ["11:45", "Entschleunigung im Alltag"],
      ["12:30", "Mittagspause", true], ["13:30", "Waldbaden-Exkursion"], ["15:30", "Transfer in den Alltag"], ["16:30", "Abschluss & Feedback"]],
    side: { icon: "FaTree", h: "Für den Wald", d: "Bitte an wetterfeste Kleidung, festes Schuhwerk und eine Sitzunterlage denken. Wir sind ca. 2 Stunden draußen." } },
  { t: "grid", title: "Check-in: Mein inneres Wetter", pill: "ÜBUNG · 15 MIN", cols: 5, lead: "Welches Wetter beschreibt Ihre Stimmung heute Morgen am besten?",
    items: [["FaSun", "Sonnig", "Klar, leicht, voller Energie"], ["FaCloudSun", "Heiter", "Überwiegend gut, ein paar Wolken"], ["FaCloud", "Bewölkt", "Etwas gedämpft, noch nicht ganz wach"],
      ["FaCloudRain", "Regnerisch", "Schwer, müde oder nachdenklich"], ["FaBolt", "Gewittrig", "Unruhig, angespannt, aufgeladen"]],
    notes: "Jede Person nennt ihr Wetter und einen Satz dazu. Anschließend: Wer hat gestern Abend die drei guten Dinge ausprobiert? Was wirkt von Tag 1 nach?" },

  // ───────────── BLOCK 5: ACHTSAMKEIT ─────────────
  { t: "section", n: "05", title: "Achtsamkeit", sub: "Achtsamkeit als Haltung und als Methode.", icon: "FaSpa" },
  { t: "quote", text: "Achtsamkeit bedeutet, auf eine bestimmte Weise aufmerksam zu sein: bewusst, im gegenwärtigen Augenblick und ohne zu bewerten.", size: 24,
    src: "Jon Kabat-Zinn, Begründer des MBSR-Programms", sub: "MBSR = Mindfulness-Based Stress Reduction, Stressbewältigung durch Achtsamkeit" },
  { t: "table", title: "Autopilot oder Achtsamkeit?", heads: ["Autopilot", "Achtsamkeit"],
    rows: [["Aufmerksamkeit", "ist in Gedanken woanders", "ist im Hier und Jetzt"], ["Reaktion", "automatisch, impulsiv", "bewusst, gewählt"],
      ["Bewertung", "sofort gut oder schlecht", "erst einmal wahrnehmen"], ["Essen", "nebenbei am Schreibtisch", "mit allen Sinnen"], ["Ergebnis", "Stress läuft ungebremst", "Raum zwischen Reiz und Reaktion"]] },
  { t: "grid", title: "Sieben Grundhaltungen der Achtsamkeit", sub: "Nach Jon Kabat-Zinn", cols: 4, vertical: false,
    items: [["1", "Nicht urteilen", "Wahrnehmen, ohne sofort zu bewerten."], ["2", "Geduld", "Dinge dürfen sich in ihrem Tempo entfalten."],
      ["3", "Anfängergeist", "Alles so sehen, als wäre es das erste Mal."], ["4", "Vertrauen", "Der eigenen Wahrnehmung trauen."],
      ["5", "Nicht erzwingen", "Nichts erreichen müssen – einfach sein."], ["6", "Akzeptanz", "Anerkennen, was gerade ist."], ["7", "Loslassen", "Nicht an Gedanken festhalten."]] },
  { t: "grid", title: "Was Achtsamkeit bewirken kann", sub: "Befunde aus Studien zu achtsamkeitsbasierten Programmen",
    items: [["FaHeartbeat", "Weniger Stress", "Teilnehmende berichten häufig ein geringeres Stresserleben und mehr Gelassenheit."],
      ["FaBullseye", "Mehr Fokus", "Aufmerksamkeit und Konzentration lassen sich durch Übung stärken."],
      ["FaHandHoldingHeart", "Emotionen regulieren", "Mehr Abstand zu Ärger und Sorgen, weniger Grübeln."]],
    notes: "Vorsichtig formulieren: Die Wirkung hängt von regelmäßiger Übung ab. Achtsamkeit ist kein Ersatz für Therapie bei psychischen Erkrankungen." },
  { t: "steps", title: "Die Rosinen-Übung", pill: "ÜBUNG · 10 MIN", sub: "Eine Rosine – als hätten Sie sie noch nie gesehen",
    items: [["Betrachten", "Farbe, Form, Falten, Glanz im Licht."], ["Fühlen", "Wie fühlt sie sich zwischen den Fingern an?"], ["Riechen", "Welcher Duft steigt auf? Was passiert im Mund?"],
      ["Schmecken", "In den Mund nehmen, nicht kauen. Dann langsam kauen."], ["Schlucken", "Bewusst schlucken und nachspüren."]],
    side: { icon: "FaAppleAlt", h: "Austausch", d: "Was war anders als sonst? Wie oft essen wir im Autopiloten?" },
    notes: "Klassische Einstiegsübung aus MBSR. Alternative: Nuss oder Apfelstück (Allergien abfragen)." },
  { t: "steps", title: "Body-Scan in Kurzform", pill: "ÜBUNG · 15 MIN", sub: "Im Sitzen oder Liegen durch den Körper wandern",
    items: [["Ankommen", "Augen schließen oder Blick senken. Den Kontakt zum Boden spüren."], ["Füße & Beine", "Wärme, Kribbeln, Druck – oder auch nichts. Alles ist in Ordnung."],
      ["Rumpf", "Rücken an der Lehne, Bauch und Brust im Atem spüren."],
      ["Schultern & Kopf", "Nacken, Kiefer, Stirn: Darf etwas loslassen?"], ["Ganzer Körper", "Den Körper als Ganzes wahrnehmen. Langsam zurückkommen."]],
    side: { icon: "FaStreetView", h: "Haltung", d: "Nichts muss sich verändern. Wir nehmen nur wahr, was da ist." } },
  { t: "letters", title: "Der 3-Minuten-Atemraum", pill: "ÜBUNG · 3 MIN", sub: "Aus der achtsamkeitsbasierten kognitiven Therapie (MBCT)",
    items: [["1", "Ankommen", "Was ist gerade da? Gedanken, Gefühle, Körperempfindungen – einfach bemerken."],
      ["2", "Sammeln", "Die Aufmerksamkeit ganz auf den Atem lenken. Ein- und Ausatmen spüren."],
      ["3", "Weiten", "Die Wahrnehmung auf den ganzen Körper und den Raum ausdehnen."]],
    foot: "Ideal zwischen zwei Terminen: wie eine Sanduhr – weit, eng, weit." },
  { t: "steps", title: "Achtsames Zuhören", pill: "PARTNERÜBUNG · 15 MIN",
    items: [["Erzählen", "A erzählt 3 Minuten: „Was mir in meiner Arbeit wichtig ist …“"], ["Zuhören", "B hört nur zu – ohne Unterbrechen, Nicken ist erlaubt."],
      ["Zusammenfassen", "B gibt in eigenen Worten wieder, was angekommen ist."], ["Wechseln", "Rollentausch – danach kurzer Austausch zu zweit."]],
    side: { icon: "FaAssistiveListeningSystems", h: "Nachspüren", d: "Wie war es, wirklich gehört zu werden? Wie schwer war es, nur zuzuhören?" } },
  { t: "reflection", title: "Wo bin ich im Autopiloten?", pill: "REFLEXION · 10 MIN",
    qs: ["Bei welchen Tätigkeiten bin ich oft gedanklich ganz woanders?", "In welchen Momenten reagiere ich automatisch, obwohl ich es anders möchte?", "Welche Alltagstätigkeit möchte ich künftig bewusst achtsam tun?", "Was könnte mich daran erinnern?"] },

  // ───────────── BLOCK 6: ATEM & KURZENTSPANNUNG ─────────────
  { t: "section", n: "06", title: "Atem und Kurzentspannung", sub: "Übungen für zwischendurch – am Schreibtisch, im Auto, vor dem Termin.", icon: "FaWind" },
  { t: "compare", title: "Der Atem als Fernbedienung", sub: "Unser Nervensystem hat Gaspedal und Bremse",
    left: { icon: "FaTachometerAlt", h: "Sympathikus – Gaspedal", items: ["Aktivierung und Leistung", "Puls und Blutdruck steigen", "Atem flach und schnell", "Einatmung betont"] },
    right: { icon: "FaSpa", h: "Parasympathikus – Bremse", items: ["Erholung und Verdauung", "Puls und Blutdruck sinken", "Atem tief und ruhig", "Ausatmung betont"] },
    foot: "Den Herzschlag können wir nicht direkt steuern – den Atem schon. Über ihn beeinflussen wir unser Nervensystem." },
  { t: "box", title: "Box Breathing", pill: "ÜBUNG · 3 MIN",
    items: [["Einatmen", "4 Sekunden ruhig durch die Nase."], ["Halten", "4 Sekunden die Luft anhalten."], ["Ausatmen", "4 Sekunden langsam durch den Mund."], ["Halten", "4 Sekunden Pause – dann von vorn."]],
    notes: "Gemeinsam 4 Runden. Wer das Anhalten unangenehm findet, lässt es weg. Einsatz: vor Gesprächen, Präsentationen, schwierigen Telefonaten." },
  { t: "big", title: "Die 4-6-Atmung", pill: "ÜBUNG · 5 MIN", num: "4-6", label: "Sek. ein  ·  Sek. aus", info: "Die verlängerte Ausatmung beruhigt das Nervensystem.",
    items: [["Aufrecht sitzen", "Füße auf dem Boden, eine Hand auf dem Bauch."], ["4 Sekunden ein", "Durch die Nase, der Bauch hebt sich."], ["6 Sekunden aus", "Langsam durch leicht geöffnete Lippen."], ["5 Minuten", "Etwa sechs Atemzüge pro Minute."]] },
  { t: "grid", title: "Notfall-Übung: 5-4-3-2-1", pill: "ÜBUNG · 3 MIN", cols: 5, lead: "Holt Sie bei Stress und Gedankenkarussell zurück ins Hier und Jetzt.", leadItalic: true,
    items: [["5", "Sehen", "Fünf Dinge, die Sie sehen"], ["4", "Fühlen", "Vier Dinge, die Sie spüren"], ["3", "Hören", "Drei Dinge, die Sie hören"], ["2", "Riechen", "Zwei Dinge, die Sie riechen"], ["1", "Schmecken", "Ein Ding, das Sie schmecken"]] },
  { t: "letters", title: "Die STOP-Methode", pill: "ÜBUNG · 1 MIN",
    items: [["S", "Stopp", "Innehalten. Einen Moment unterbrechen, was Sie gerade tun."], ["T", "Tief atmen", "Einen bewussten, tiefen Atemzug nehmen."],
      ["O", "Observieren", "Beobachten: Was denke, fühle, spüre ich gerade?"], ["P", "Prüfen & weiter", "Was ist jetzt wichtig? Dann bewusst weitermachen."]],
    notes: "Gut geeignet vor dem Beantworten einer ärgerlichen E-Mail oder vor dem Abheben des Telefons." },
  { t: "steps", title: "Bewegte Pause am Arbeitsplatz", pill: "ÜBUNG · 5 MIN",
    items: [["Schultern kreisen", "Fünfmal nach hinten, fünfmal nach vorn – langsam und groß."], ["Nacken dehnen", "Kopf sanft zur Seite neigen, 20 Sekunden halten, Seite wechseln."],
      ["Aufrichten", "Aufstehen, Arme nach oben strecken, auf die Zehenspitzen gehen."], ["Augen entspannen", "Handflächen warm reiben und auf die geschlossenen Augen legen."],
      ["In die Ferne schauen", "Aus dem Fenster in die Weite blicken – mindestens 20 Sekunden."]],
    side: { icon: "FaChild", h: "Hinweis", d: "Alles in Ihrem Tempo und ohne Schmerzen. Bewegungen dürfen klein sein." } },
  { t: "grid", title: "Welche Übung wann?", sub: "Ihr Werkzeugkasten für den Arbeitstag",
    items: [["FaSun", "Morgens", "3-Minuten-Atemraum oder 4-6-Atmung vor dem ersten Blick ins Postfach."],
      ["FaPhoneAlt", "Vor Gesprächen", "Box Breathing – ruhig und konzentriert ins Gespräch."],
      ["FaExclamationTriangle", "Akuter Ärger", "STOP-Methode oder physiologischer Seufzer."],
      ["FaRandom", "Grübeln", "5-4-3-2-1 – zurück ins Hier und Jetzt."],
      ["FaLaptop", "Nach langem Sitzen", "Bewegte Pause und Blick in die Ferne."],
      ["FaMoon", "Abends", "Body-Scan oder Progressive Muskelentspannung."]] },

  // ───────────── BLOCK 7: ENTSCHLEUNIGUNG ─────────────
  { t: "section", n: "07", title: "Entschleunigung", sub: "Kleine Pausen mit großer Wirkung.", icon: "FaHourglassHalf" },
  { t: "big", title: "Warum wir Pausen brauchen", num: "90", label: "Minuten", info: "Unsere Leistungsfähigkeit verläuft in Wellen – nicht als gerade Linie.",
    items: [["Leistungskurve", "Nach etwa 90 Minuten konzentrierter Arbeit sinkt die Aufmerksamkeit spürbar."], ["Früh pausieren", "Kurze Pausen wirken am besten, bevor wir erschöpft sind."], ["Kleine Pausen zählen", "Mehrere Kurzpausen erholen oft mehr als eine lange."]],
    notes: "Ultradiane Rhythmen (Nathaniel Kleitman): Richtwert, individuell verschieden." },
  { t: "grid", title: "Mikropausen: 1 bis 5 Minuten", pill: "ALLTAGSTIPP",
    items: [["FaWindowMaximize", "Fensterblick", "Bewusst in die Ferne und ins Grüne schauen."], ["FaTint", "Wasser trinken", "Ein Glas Wasser – langsam und bewusst."],
      ["FaWalking", "Kurzer Gang", "Einmal über den Flur oder die Treppe nehmen."], ["FaWind", "Drei Atemzüge", "Tief ausatmen, bevor die nächste Aufgabe beginnt."],
      ["FaDoorOpen", "Frische Luft", "Fenster öffnen oder kurz vor die Tür treten."], ["FaSmile", "Kurzer Plausch", "Ein freundliches Wort mit Kolleg:innen – ohne Arbeitsthema."]] },
  { t: "arrows", title: "Pausenkiller und Gegenmittel", heads: ["Pausenkiller", "Gegenmittel"],
    rows: [["„Ich mache Pause, wenn ich fertig bin.“", "Pausen fest im Kalender eintragen."], ["Mittagessen am Schreibtisch", "Bewusst den Arbeitsplatz verlassen."],
      ["In der Pause aufs Handy schauen", "Pause ohne Bildschirm – Augen und Kopf erholen sich."], ["„Die anderen machen ja auch keine.“", "Pausen gemeinsam verabreden."]] },
  { t: "grid", title: "Digitale Entschleunigung", pill: "ALLTAGSTIPP",
    items: [["FaEnvelope", "E-Mail-Zeiten", "Postfach zu festen Zeiten prüfen, z. B. 3-mal täglich."], ["FaBellSlash", "Stumm schalten", "Pop-ups und Töne für E-Mails abschalten."],
      ["FaWindowRestore", "Ein Fenster", "Nur das Programm öffnen, an dem Sie gerade arbeiten."], ["FaCalendarAlt", "Fokuszeiten", "Störungsfreie Zeitblöcke im Kalender eintragen."],
      ["FaMobileAlt", "Handy weg", "Privates Handy außer Sichtweite legen."], ["FaMoon", "Feierabend", "Keine Dienst-E-Mails nach Dienstschluss."]] },
  { t: "steps", title: "Mein Pausenplan", pill: "ÜBUNG · 10 MIN",
    items: [["Ist-Zustand", "Wann und wie mache ich derzeit Pausen? Seien Sie ehrlich."], ["Zeitfenster finden", "Tragen Sie drei feste Pausen in Ihren typischen Arbeitstag ein."],
      ["Inhalte wählen", "Was tun Sie in jeder Pause? Bewegung, Atem, frische Luft …"], ["Erinnerung", "Wie erinnern Sie sich? Kalender, Wecker, feste Rituale."]],
    side: { icon: "FaCalendarAlt", h: "Tipp", d: "Pausen wie wichtige Termine behandeln – mit sich selbst." } },
  { t: "steps", title: "Tipp: Ein Feierabend-Ritual", pill: "ALLTAGSTIPP", lead: "Ein bewusster Übergang hilft, die Arbeit im Büro zu lassen.",
    items: [["Rückblick", "Was habe ich heute geschafft? Drei Dinge notieren."], ["Offenes parken", "Die wichtigsten Aufgaben für morgen aufschreiben."],
      ["Aufräumen", "Schreibtisch ordnen, Computer herunterfahren."], ["Übergang", "Ein fester Abschluss: Tür schließen, tief durchatmen, der Weg nach Hause als Pause."]],
    side: { icon: "FaDoorOpen", h: "Satz für den Abschluss", d: "„Für heute ist es genug. Morgen geht es weiter.“" } },

  // ───────────── BLOCK 8: WALDBADEN ─────────────
  { t: "section", n: "08", title: "Waldbaden", sub: "Shinrin-Yoku – mit allen Sinnen in die Atmosphäre des Waldes eintauchen.", icon: "FaTree" },
  { t: "grid", title: "Was ist Waldbaden?", sub: "Shinrin-Yoku: In den 1980er-Jahren in Japan geprägt",
    items: [["FaTree", "Eintauchen", "Kein Sport, keine Wanderung: langsam und absichtslos im Wald sein."], ["FaEye", "Alle Sinne", "Bewusst sehen, hören, riechen, tasten und spüren."], ["FaDove", "Stille", "Wenig sprechen, viel wahrnehmen – das Tempo drosseln."]] },
  { t: "grid", title: "Wie der Wald auf uns wirkt", sub: "Was Studien zum Waldaufenthalt nahelegen",
    items: [["FaHeartbeat", "Körper", "Hinweise auf niedrigeren Puls und Blutdruck sowie weniger Stresshormone."], ["FaSmile", "Stimmung", "Viele Menschen fühlen sich danach ruhiger, erholter und klarer."],
      ["FaBrain", "Aufmerksamkeit", "Natur erholt die gerichtete Aufmerksamkeit (Attention Restoration Theory)."]],
    notes: "Studien u. a. von Qing Li und Yoshifumi Miyazaki; Attention Restoration Theory nach Rachel und Stephen Kaplan. Wirkung nicht überhöhen: Waldbaden ist ein Erholungsangebot, keine Therapie." },
  { t: "grid", title: "Hinweise für unsere Exkursion",
    items: [["FaTshirt", "Kleidung", "Wetterfeste Kleidung und festes Schuhwerk."], ["FaMobileAlt", "Handy", "Stumm schalten und in der Tasche lassen."], ["FaDove", "Schweigen", "Zwischen den Stationen gehen wir schweigend."],
      ["FaShoePrints", "Tempo", "Langsamer, als Sie es gewohnt sind."], ["FaBug", "Sicherheit", "Auf Wegen bleiben, abends nach Zecken schauen."], ["FaHandshake", "Freiwilligkeit", "Jede Übung ist ein Angebot."]],
    notes: "Vorab klären: Mobilitätseinschränkungen, Allergien, Notfallnummer. Route und Sitzplätze vorher erkunden." },
  { t: "steps", title: "Station 1: Ankommen im Wald", pill: "IM WALD · 20 MIN",
    items: [["Schwelle", "Wir überschreiten bewusst eine „Schwelle“ und lassen den Alltag hinter uns."], ["Stehen", "Füße hüftbreit, Augen schließen, den Boden unter den Füßen spüren."],
      ["Lauschen", "Was hören Sie nah, was in der Ferne? Vögel, Wind, Blätter."], ["Riechen", "Tief einatmen: Wie riecht der Wald heute?"]],
    side: { icon: "FaTree", h: "Impuls", d: "„Was nehme ich wahr, wenn ich nichts erreichen muss?“" } },
  { t: "steps", title: "Station 2: Achtsames Gehen", pill: "IM WALD · 20 MIN",
    items: [["Langsam gehen", "Deutlich langsamer als gewohnt – Schritt für Schritt."], ["Füße spüren", "Abrollen, Aufsetzen, Gewicht verlagern bewusst wahrnehmen."],
      ["Was bewegt sich?", "Achten Sie auf alles, was sich im Wald bewegt."], ["Im Schweigen", "Wir gehen schweigend hintereinander."]],
    side: { icon: "FaShoePrints", h: "Impuls", d: "„Der Weg ist das Ziel – ich komme nirgendwo an, ich bin schon da.“" } },
  { t: "steps", title: "Station 3: Mein Sitzplatz", pill: "IM WALD · 25 MIN",
    items: [["Platz wählen", "Suchen Sie sich in Sichtweite einen Platz, der Sie anspricht."], ["Einfach sitzen", "Rund 15 Minuten nur sitzen, schauen, lauschen, atmen."],
      ["Nichts tun", "Kein Handy, kein Ziel. Gedanken dürfen kommen und gehen."], ["Rückruf", "Ein Signal ruft die Gruppe zurück."]],
    side: { icon: "FaLeaf", h: "Impuls", d: "„Was sehe ich, wenn ich lange genug hinschaue?“" } },
  { t: "steps", title: "Station 4: Begegnung mit einem Baum", pill: "IM WALD · 20 MIN",
    items: [["Baum finden", "Lassen Sie sich von einem Baum „einladen“."], ["Ertasten", "Rinde, Moos, Wurzeln – mit den Händen und geschlossenen Augen."],
      ["Anlehnen", "Mit dem Rücken an den Stamm lehnen, gemeinsam atmen."], ["Naturgeschenk", "Etwas Kleines mitnehmen, das Sie berührt hat: ein Blatt, ein Zapfen."]],
    side: { icon: "FaTree", h: "Impuls", d: "Ein Baum steht fest, weil seine Wurzeln tief reichen. Was sind meine Wurzeln?" } },
  { t: "reflection", title: "Abschlusskreis im Wald", pill: "REFLEXION · 20 MIN",
    qs: ["Was hat mich im Wald berührt?", "Wofür steht mein Naturgeschenk?", "Was möchte ich von dieser Ruhe mit in den Alltag nehmen?"],
    notes: "Im Kreis stehend oder sitzend. Wer mag, legt sein Naturgeschenk in die Mitte und sagt ein bis zwei Sätze. Optional Tee aus der Thermoskanne." },

  // ───────────── BLOCK 9: TRANSFER ─────────────
  { t: "section", n: "09", title: "Transfer in den Berufsalltag", sub: "Persönliche Strategien für mehr Ruhe und Klarheit.", icon: "FaRoute" },
  { t: "grid", title: "Rückblick: Unser Werkzeugkoffer", cols: 4, vertical: false,
    items: [["FaBalanceScale", "Energiebilanz", "Räuber und Spender kennen"], ["FaFeather", "Erlauber", "Innere Antreiber entschärfen"], ["FaHandPaper", "Einflussbereich", "Kraft dort einsetzen, wo sie wirkt"],
      ["FaPen", "ABC-Analyse", "Bewertungen prüfen"], ["FaWind", "Atemübungen", "Box, 4-6, Seufzer"], ["FaSpa", "Achtsamkeit", "Atemraum, Body-Scan, STOP"],
      ["FaHourglassHalf", "Pausen", "Mikropausen und Rituale"], ["FaTree", "Natur", "Regelmäßig ins Grüne"]] },
  { t: "steps", title: "Meine persönlichen Strategien", pill: "ÜBUNG · 15 MIN",
    items: [["Auswählen", "Wählen Sie drei Werkzeuge, die Sie wirklich ansprechen."], ["Konkretisieren", "Wann, wo und wie oft wollen Sie sie anwenden?"],
      ["Anker setzen", "Woran koppeln Sie die Übung? Z. B. „Nach dem ersten Kaffee …“"], ["Hindernisse", "Was könnte Sie abhalten – und was tun Sie dann?"]],
    side: { icon: "FaClipboardCheck", h: "Weniger ist mehr", d: "Lieber eine kleine Übung täglich als zehn gute Vorsätze, die im Alltag untergehen." } },
  { t: "letters", title: "Ziele erreichen mit WOOP", sub: "Nach Gabriele Oettingen", pill: "ÜBUNG · 15 MIN", hi: 3,
    items: [["W", "Wish", "Was wünsche ich mir für die nächsten vier Wochen? Konkret und erreichbar."], ["O", "Outcome", "Was wäre das beste Ergebnis? Wie fühlt es sich an?"],
      ["O", "Obstacle", "Welches innere Hindernis könnte mich stoppen?"], ["P", "Plan", "Wenn [Hindernis] auftritt, dann werde ich [Handlung]."]] },
  { t: "arrows", title: "Wenn-Dann-Pläne", pill: "ALLTAGSTIPP", heads: ["Wenn …", "… dann"],
    rows: [["Wenn ich morgens den PC starte,", "atme ich dreimal tief durch."], ["Wenn ich mich über eine Mail ärgere,", "wende ich STOP an."],
      ["Wenn es 12:30 Uhr ist,", "verlasse ich meinen Platz."], ["Wenn ich Feierabend mache,", "notiere ich drei gute Dinge."]],
    foot: "Konkrete Wenn-Dann-Pläne erhöhen die Chance deutlich, dass Vorsätze umgesetzt werden (Peter Gollwitzer)." },
  { t: "steps", title: "Brief an mich selbst", pill: "ÜBUNG · 15 MIN",
    items: [["Schreiben", "Schreiben Sie sich einen Brief: Was möchte ich mir in sechs Wochen in Erinnerung rufen?"], ["Inhalte", "Erkenntnisse, Vorsätze, ermutigende Worte, Ihr Naturgeschenk."],
      ["Verschließen", "Adressieren und verschließen Sie den Umschlag."], ["Überraschung", "Wir schicken Ihnen den Brief in etwa sechs Wochen zu."]],
    side: { icon: "FaEnvelope", h: "Warum?", d: "Der Brief erinnert Sie, wenn der Alltag die guten Vorsätze verdrängt hat – in Ihren eigenen Worten." } },
  { t: "steps", title: "Transfer-Tandem", pill: "PARTNERÜBUNG · 10 MIN",
    items: [["Tandem bilden", "Finden Sie eine Person aus der Gruppe als Transfer-Partner:in."], ["Vorhaben teilen", "Erzählen Sie einander Ihre drei Strategien und Ihren WOOP-Plan."],
      ["Termin vereinbaren", "Vereinbaren Sie ein kurzes Telefonat in drei bis vier Wochen."], ["Nachfragen", "Was klappt? Was nicht? Was brauche ich noch?"]],
    side: { icon: "FaHandsHelping", h: "Gemeinsam dranbleiben", d: "Wer sein Vorhaben mit anderen teilt, bleibt eher dabei. Das Tandem darf auch per Telefon stattfinden." } },
  { t: "summary", title: "Das Wichtigste in Kürze",
    items: [["Stress entsteht im Kopf mit", "Bewertungen prüfen und Antreiber entschärfen."], ["Resilienz ist trainierbar", "Unser Gehirn lernt in jedem Alter."],
      ["Achtsamkeit schafft Raum", "Zwischen Reiz und Reaktion liegt unsere Freiheit."], ["Pausen sind Leistung", "Kleine Pausen, große Wirkung."], ["Natur heilt", "Der Wald ist ein Kraftort vor der Haustür."]],
    side: { icon: "FaComments", h: "Offene Fragen?", d: "Was ist noch unklar? Was möchten Sie noch loswerden?" } },
  { t: "reflection", title: "Abschlussrunde & Feedback", pill: "REFLEXION · 20 MIN",
    qs: ["Hat sich mein Anliegen vom Anfang erfüllt?", "Was nehme ich mit in meinen Arbeitsalltag?", "Wie voll ist mein Energietank jetzt? (Energie-Barometer)", "Was möchte ich der Gruppe noch sagen?"],
    notes: "Anliegen-Karten von Tag 1 von der Pinnwand nehmen. Energie-Barometer wiederholen und mit dem Morgen von Tag 1 vergleichen. Feedbackbogen austeilen." },
  { t: "thanks", title: "Vielen Dank!", sub: "Bleiben Sie achtsam mit sich – und gönnen Sie sich regelmäßig Zeit im Grünen.",
    meta: "Kommen Sie gut nach Hause.", icon: "FaLeaf" },
];

(async () => {
  if (S.length !== 100) console.warn("WARN: slide count = " + S.length);
  const pres = await createDeck({ logo: path.join(__dirname, "logo_dark.png"), title: "Mentale Stärke, Achtsamkeit und Entschleunigung im Arbeitsalltag", slides: S });
  await pres.writeFile({ fileName: path.join(__dirname, "Zweitagesseminar_Mentale_Staerke_Achtsamkeit.pptx") });
  console.log("slides:", S.length);
})();
