// Bildkatalog: Motiv (de), Bildplatz (portrait 4:5 | wide 16:9) und Prompt für den Bildgenerator (en)
const STYLE =
  "photorealistic photograph, natural light, calm and authentic mood, warm muted colors with subtle amber accents, " +
  "soft contrast, shallow depth of field, shot on a full-frame camera with a 35mm lens, editorial documentary style, " +
  "no text, no logos, no watermark";

const IMAGES = {
  "01": { slot: "portrait", de: "Frau um die 55 steht mit geschlossenen Augen auf einem Waldweg im Morgenlicht",
    prompt: "A woman in her mid-fifties with short grey hair stands on a quiet forest path in northern Germany, eyes closed, relaxed shoulders, soft morning sunlight filtering through beech trees, light mist, seen from a slight side angle" },
  "02": { slot: "portrait", de: "Mann um die 60 am Bürofenster, Kaffeetasse in der Hand, blickt ruhig ins Grüne",
    prompt: "A man around sixty in a casual shirt stands at a large office window of a German public administration building, holding a coffee mug, looking calmly out at green trees, soft daylight, tidy modern office in the background, out of focus" },
  "03": { slot: "portrait", de: "Überladener Schreibtisch mit Aktenstapeln, Telefon und Bildschirm, Hände an den Schläfen",
    prompt: "Close-up of a cluttered office desk with tall stacks of paper files, a ringing desk phone, sticky notes and a monitor full of emails, the hands of a middle-aged employee pressed to their temples at the edge of the frame, cool office light with a warm desk lamp" },
  "04": { slot: "portrait", de: "Birken im Wind in der Moorlandschaft des Teufelsmoors",
    prompt: "Slender birch trees bending in strong wind in the Teufelsmoor moorland near Worpswede, northern Germany, dramatic sky with breaking clouds, golden late-afternoon light on the white bark, resilience and flexibility" },
  "05": { slot: "portrait", de: "Wolken spiegeln sich in einem stillen Moorsee",
    prompt: "A perfectly still dark moor lake in northern Germany reflecting drifting white clouds and a blue sky, reeds and heather at the shore, calm, contemplative, symmetrical composition" },
  "06": { slot: "portrait", de: "Buchenwald mit Morgennebel und Sonnenstrahlen über einem Waldweg",
    prompt: "A mixed beech and oak forest in Lower Saxony at early morning, sunbeams breaking through light mist over a soft forest path, fresh green leaves, peaceful and inviting" },
  "07": { slot: "portrait", de: "Hände halten eine Tasse Tee, Dampf steigt auf, weiches Fensterlicht",
    prompt: "Close-up of two hands of a person in their fifties gently holding a ceramic cup of herbal tea, visible steam rising, soft window light, knitted sleeve, wooden table, mindful and cozy" },
  "08": { slot: "portrait", de: "Person 50+ sitzt aufrecht mit geschlossenen Augen im hellen Seminarraum und atmet",
    prompt: "A man in his late fifties sits upright on a simple wooden chair in a bright seminar room, eyes closed, one hand resting on his belly, breathing calmly, large windows with trees outside, soft natural light" },
  "09": { slot: "portrait", de: "Leere Holzbank unter einem alten Baum im Abendlicht",
    prompt: "An empty weathered wooden bench under a large old oak tree at the edge of a meadow in northern Germany, warm evening light, long soft shadows, invitation to pause" },
  "10": { slot: "portrait", de: "Kleine Gruppe Erwachsener geht langsam auf einem Waldweg, von hinten fotografiert",
    prompt: "A small group of five adults aged 45 to 65 in outdoor jackets walking slowly and silently in single file along a mossy forest path lined with ferns, seen from behind, dappled sunlight, forest bathing" },
  "11": { slot: "portrait", de: "Schreibtisch mit kleiner Pflanze und Notizbuch mit handgeschriebenem Plan",
    prompt: "A calm, tidy office desk in the morning with a small green plant, an open notebook with a handwritten weekly plan and a pen, a cup of coffee, sunlight falling across the desk, fresh start" },
  "12": { slot: "portrait", de: "Blick nach oben in ein sonnendurchflutetes Blätterdach",
    prompt: "Looking straight up into a sunlit canopy of beech leaves, sun star shining through the branches, vibrant green and golden tones, uplifting and grateful mood" },
  "13": { slot: "portrait", de: "Frau um die 55 fährt lächelnd Fahrrad auf einem Feldweg",
    prompt: "A smiling woman in her mid-fifties riding a bicycle along a country lane between fields in northern Germany, light summer evening, relaxed, healthy and content, slight motion" },
  "14": { slot: "portrait", de: "Kleine Pflanze wächst durch einen Riss im Pflaster",
    prompt: "Macro photograph of a small green seedling growing through a crack in grey paving stones, morning dew, soft backlight, symbol of resilience" },
  "15": { slot: "portrait", de: "Ruhige Wasseroberfläche mit einem einzelnen fallenden Tropfen",
    prompt: "A calm dark water surface with a single water drop creating concentric ripples, soft reflections of sky, minimalist, contemplative" },
  "16": { slot: "portrait", de: "Hand berührt sanft ein Moospolster im Wald",
    prompt: "Close-up of a hand of a person in their fifties gently touching a soft cushion of green moss on a forest floor, morning light, fine details, mindful touch" },
  "17": { slot: "wide", de: "Holzsteg an einem stillen See bei Sonnenaufgang",
    prompt: "A wooden jetty reaching into a calm lake at sunrise in northern Germany, light mist on the water, reeds, peaceful place to recharge" },
  "18": { slot: "wide", de: "Hand zeichnet eine Lebenslinie mit Höhen und Tiefen auf Papier",
    prompt: "Top-down view of a hand drawing a wavy life line with ups and downs on a large sheet of paper with a pencil, small handwritten notes along the curve, seminar table, warm light" },
  "19": { slot: "wide", de: "Nahaufnahme von Rosinen in einer kleinen Keramikschale",
    prompt: "Macro photograph of a few raisins in a small handmade ceramic bowl on a wooden table, one raisin held between thumb and finger, soft side light showing the wrinkled texture" },
  "20": { slot: "wide", de: "Person liegt entspannt mit Decke auf einer Matte im Seminarraum",
    prompt: "A woman in her fifties lying relaxed on a yoga mat under a light woollen blanket in a bright seminar room, eyes closed, head on a small cushion, soft daylight, body scan relaxation" },
  "21": { slot: "wide", de: "Zwei Kolleg:innen 50+ im aufmerksamen Gespräch am Tisch",
    prompt: "Two colleagues in their fifties sitting at a small table in a seminar room, one speaking, the other listening attentively with open body language, warm natural light, authentic conversation" },
  "22": { slot: "wide", de: "Mann um die 60 streckt sich am Schreibtisch",
    prompt: "A man around sixty standing beside his office desk stretching both arms above his head, smiling slightly, window with daylight, computer in the background, healthy break" },
  "23": { slot: "wide", de: "Jacke an der Bürotür, Abendlicht – Feierabend",
    prompt: "An office door slightly open with a jacket and bag hanging on a hook next to it, empty tidy desk and switched-off monitor in warm evening light, end of the working day" },
  "24": { slot: "wide", de: "Waldweg führt wie durch ein Tor in einen Buchenwald",
    prompt: "A forest path entering a beech forest between two large tree trunks forming a natural gateway, soft morning light, inviting threshold into the woods" },
  "25": { slot: "wide", de: "Wanderschuhe auf weichem Waldboden mit Laub",
    prompt: "Low-angle close-up of hiking boots slowly stepping on a soft forest floor covered with brown leaves and moss, shallow depth of field, mindful walking" },
  "26": { slot: "wide", de: "Sitzkissen auf Moos an einer kleinen Waldlichtung",
    prompt: "A small sitting pad placed on a mossy tree stump at the edge of a quiet forest clearing, ferns around, sunlight patches, invitation to sit still" },
  "27": { slot: "wide", de: "Hände berühren die Rinde eines alten Baumes",
    prompt: "Close-up of two hands resting on the textured bark of an old oak tree, eyes-closed feeling, dappled forest light, connection with nature" },
  "28": { slot: "wide", de: "Handgeschriebener Brief und Umschlag auf einem Holztisch",
    prompt: "A handwritten letter in German cursive with a fountain pen and an envelope on a wooden table, a dried beech leaf beside it, warm soft light, personal and hopeful" },
  "29": { slot: "wide", de: "Zwei Kolleg:innen 50+ gehen im Gespräch einen Weg entlang",
    prompt: "Two colleagues in their fifties walking side by side along a tree-lined path, talking and laughing, seen from a slight distance, autumn light, supportive partnership" },
  "30": { slot: "portrait", de: "Frau um die 52 steht am offenen Fenster, frische Luft, entspannter Gesichtsausdruck",
    prompt: "A woman around fifty-two with shoulder-length hair stands at an open window of a bright office, eyes half closed, breathing in fresh air, a light breeze moving the curtain, relieved and calm expression, soft natural daylight" },
  "31": { slot: "portrait", de: "Frau und Mann um die 55 gehen im Gespräch einen herbstlichen Weg entlang",
    prompt: "A woman and a man both in their mid-fifties walking side by side on a tree-lined autumn path in northern Germany, talking openly and smiling, seen from a slight distance, warm golden light, mutual understanding" },
  "32": { slot: "wide", de: "Frau 50+ am Schreibtisch mit Wasserglas, atmet ruhig mit geschlossenen Augen",
    prompt: "A woman in her early fifties sitting at an office desk, eyes closed, one hand on her chest, a glass of cold water and a small desk fan beside her, calmly breathing through a hot flush, soft daylight, dignified and calm" },
};

module.exports = { IMAGES, STYLE };
