// Zusatzmodul: Menopause, Stress und Achtsamkeit (20 Folien)
const path = require("path");
const { createDeck } = require("./layouts");
const { IMAGES } = require("./images");

const S = [
  { t: "cover", img: "30", kicker: "ZUSATZMODUL", title: "Menopause, Stress und Achtsamkeit", size: 36,
    sub: "Wechseljahre bei Frauen und Männern verstehen – und gelassener durch diese Lebensphase gehen",
    meta: "Mentale Stärke, Achtsamkeit und Entschleunigung im Arbeitsalltag", icon: "FaVenusMars",
    notes: "Behutsam einleiten: Das Thema betrifft viele Teilnehmende direkt oder als Partner:in und Kolleg:in. Freiwilligkeit betonen – niemand muss über eigene Beschwerden sprechen. Das Modul ersetzt keine ärztliche Beratung." },
  { t: "quote", img: "31", text: "Die Wechseljahre sind keine Krankheit – aber sie verdienen Aufmerksamkeit.",
    src: "Grundhaltung dieses Moduls", sub: "Eine natürliche Lebensphase, die Körper, Psyche und Arbeitsalltag spürbar verändern kann – bei Frauen deutlich, bei Männern leiser." },
  { t: "grid", title: "Warum das Thema in den Arbeitsalltag gehört",
    items: [["FaUsers", "Viele sind betroffen", "Frauen zwischen 45 und 60 sind eine große Gruppe in der Verwaltung – oft mit viel Erfahrung und Verantwortung."],
      ["FaLock", "Noch immer ein Tabu", "Über Wechseljahre wird selten gesprochen. Beschwerden werden verschwiegen oder falsch gedeutet."],
      ["FaHeartbeat", "Gesundheit und Leistung", "Schlafmangel, Hitzewallungen und Stress wirken direkt auf Konzentration, Wohlbefinden und Zusammenarbeit."]],
    notes: "Hinweis: Auch Männer erleben hormonelle Veränderungen – und sie sind Kollegen, Führungskräfte und Partner von Frauen in den Wechseljahren." },

  // Grundlagen Frauen
  { t: "letters", title: "Die Phasen der Wechseljahre", sub: "Klimakterium – ein Übergang über mehrere Jahre", hi: 1,
    items: [["1", "Perimenopause", "Beginnt oft Mitte 40. Der Zyklus wird unregelmäßig, erste Beschwerden können auftreten."],
      ["2", "Menopause", "Die letzte Regelblutung. Sie steht erst fest, wenn zwölf Monate keine Blutung mehr kam."],
      ["3", "Postmenopause", "Die Zeit danach. Der Körper stellt sich auf ein neues hormonelles Gleichgewicht ein."]],
    foot: "Die Wechseljahre sind ein Prozess, kein Stichtag – und jede Frau erlebt ihn anders." },
  { t: "big", title: "Die Menopause in Zahlen", num: "51", label: "Jahre – durchschnittliches Alter der letzten Regelblutung",
    info: "Der Zeitpunkt ist individuell sehr verschieden.",
    items: [["Früher Beginn", "Die Perimenopause beginnt oft schon Mitte 40 – mitten im Berufsleben."],
      ["Lange Dauer", "Beschwerden können mehrere Jahre anhalten, bei manchen Frauen auch länger."],
      ["Unterschiedlich stark", "Ein Teil der Frauen hat kaum Beschwerden, etwa jede dritte ist stark belastet."]],
    notes: "Zahlen als Orientierung: Das Durchschnittsalter der Menopause liegt in Deutschland bei etwa 51 bis 52 Jahren. Angaben zu Dauer und Häufigkeit schwanken je nach Studie." },
  { t: "grid", title: "Was hormonell passiert",
    items: [["FaVenus", "Östrogen sinkt", "Wirkt im ganzen Körper: auf Temperaturregelung, Schlaf, Stimmung, Gehirn, Knochen und Haut."],
      ["FaMoon", "Progesteron sinkt", "Oft als Erstes. Es wirkt beruhigend und schlaffördernd – fehlt es, wird der Schlaf unruhiger."],
      ["FaSyncAlt", "Starke Schwankungen", "Gerade in der Perimenopause schwanken die Hormone stark. Das macht Beschwerden schwer vorhersehbar."]] },
  { t: "grid", title: "Häufige Beschwerden bei Frauen",
    items: [["FaTemperatureHigh", "Hitzewallungen", "Plötzliche Hitze, Schwitzen, Herzklopfen – tagsüber und als Nachtschweiß."],
      ["FaBed", "Schlafstörungen", "Einschlafen fällt schwer, nächtliches Aufwachen, oft durch Nachtschweiß."],
      ["FaTheaterMasks", "Stimmung", "Reizbarkeit, Stimmungsschwankungen, Ängstlichkeit."],
      ["FaBrain", "Konzentration", "Vergesslichkeit, Wortfindungsprobleme, „Nebel im Kopf“."],
      ["FaChild", "Körper", "Gelenk- und Muskelschmerzen, Gewichtsveränderungen, trockene Haut."],
      ["FaBatteryQuarter", "Erschöpfung", "Weniger Energie und Belastbarkeit – oft verstärkt durch schlechten Schlaf."]],
    notes: "Viele Frauen deuten Konzentrations- und Stimmungsprobleme zunächst nicht als Wechseljahresbeschwerden – oder befürchten eine beginnende Demenz. Aufklärung entlastet." },

  // Stress & Menopause
  { t: "compare", title: "Östrogen und Stress", sub: "Warum Stress in den Wechseljahren oft stärker wirkt",
    left: { icon: "FaShieldAlt", h: "Was Östrogen leistet", items: ["Dämpft die Stressachse", "Unterstützt Botenstoffe wie Serotonin", "Hilft bei der Temperaturregelung", "Fördert erholsamen Schlaf"] },
    right: { icon: "FaExclamationTriangle", h: "Wenn es weniger wird", items: ["Stressreaktionen fallen oft stärker aus", "Die Stimmung wird störanfälliger", "Stress kann Hitzewallungen auslösen", "Der Schlaf wird leichter und kürzer"] },
    foot: "Die Wechseljahre machen nicht „schwach“ – aber das Nervensystem reagiert empfindlicher. Umso wichtiger sind gute Strategien.",
    notes: "Vereinfachte Darstellung: Östrogen beeinflusst u. a. die Hypothalamus-Hypophysen-Nebennieren-Achse und Neurotransmitter wie Serotonin." },
  { t: "grid", title: "Der Teufelskreis aus Hormonen und Stress", cols: 5,
    items: [["1", "Hormone schwanken", "Östrogen und Progesteron nehmen ab und schwanken."],
      ["2", "Nächte werden unruhig", "Nachtschweiß und Wachphasen rauben Erholung."],
      ["3", "Weniger Puffer", "Müdigkeit senkt die Belastbarkeit am Tag."],
      ["4", "Mehr Stress", "Kleinigkeiten regen auf, Gedanken kreisen."],
      ["5", "Mehr Beschwerden", "Stress verstärkt Hitzewallungen und stört den Schlaf."]],
    notes: "Die gute Nachricht: Ein Kreislauf lässt sich an jeder Stelle unterbrechen – durch Schlafroutinen, Stressbewältigung, Bewegung, Achtsamkeit und bei Bedarf medizinische Behandlung." },
  { t: "grid", title: "Herausforderungen am Arbeitsplatz",
    items: [["FaFire", "Hitzewallung im Termin", "Mitten im Bürgergespräch oder in der Besprechung – und die Sorge, dass es andere sehen."],
      ["FaBrain", "Konzentration", "Komplexe Vorgänge fallen schwerer, wenn der Schlaf fehlt."],
      ["FaTheaterMasks", "Scham und Schweigen", "Viele Frauen erklären Beschwerden lieber anders, als die Wechseljahre zu nennen."],
      ["FaHome", "Doppelbelastung", "Gleichzeitig pflegebedürftige Eltern, Kinder im Umbruch, berufliche Verantwortung."],
      ["FaThermometerHalf", "Arbeitsumgebung", "Warme Räume, Dienstkleidung, fehlende Fenster oder Rückzugsmöglichkeiten."],
      ["FaCommentDots", "Unverständnis", "Sprüche und Unwissen im Team verstärken den Druck."]] },

  // Männer
  { t: "table", title: "Und die Männer?", sub: "Hormonelle Veränderungen verlaufen bei Männern anders", heads: ["Frauen", "Männer"],
    rows: [["Hormon", "Östrogen und Progesteron", "Testosteron"], ["Verlauf", "deutlicher Abfall über wenige Jahre", "langsamer Rückgang, etwa 1 % pro Jahr ab 40"],
      ["Kennzeichen", "Ende der Regelblutung", "kein klarer Endpunkt"], ["Beschwerden", "bei den meisten Frauen", "deutlich nur bei einem Teil der Männer"],
      ["Begriff", "Wechseljahre, Menopause", "„Andropause“ – medizinisch: Testosteronmangel"]],
    notes: "Der Begriff „Wechseljahre des Mannes“ ist umstritten. Ein behandlungsbedürftiger Testosteronmangel betrifft nur einen Teil der älteren Männer und wird ärztlich über Symptome und Blutwerte festgestellt." },
  { t: "grid", title: "Mögliche Anzeichen bei Männern",
    items: [["FaBatteryQuarter", "Antriebslosigkeit", "Weniger Energie, schnellere Erschöpfung."], ["FaBolt", "Reizbarkeit", "Gereiztheit, geringere Frustrationstoleranz."],
      ["FaBed", "Schlaf", "Schlechterer Schlaf, häufiges Aufwachen, auch Schwitzen."], ["FaHeart", "Weniger Lust", "Nachlassende Libido und Leistungsfähigkeit."],
      ["FaWeight", "Körper", "Mehr Bauchfett, weniger Muskelkraft."], ["FaBrain", "Konzentration", "Nachlassende Konzentration und Motivation."]],
    notes: "Diese Anzeichen sind unspezifisch – sie können auch Folge von Stress, Schlafmangel, Übergewicht, Depression oder anderen Erkrankungen sein. Deshalb ärztlich abklären lassen." },
  { t: "iconList", title: "Stress, Lebensstil und Testosteron",
    items: [["FaBolt", "Dauerstress", "Anhaltend hohe Cortisolwerte können die Testosteronbildung hemmen."],
      ["FaBed", "Schlafmangel", "Ein großer Teil des Testosterons wird im Schlaf gebildet."],
      ["FaWineGlassAlt", "Alkohol und Übergewicht", "Beide senken den Testosteronspiegel zusätzlich."],
      ["FaDumbbell", "Bewegung", "Regelmäßige Bewegung, vor allem Krafttraining, wirkt unterstützend."]],
    side: { h: "Männer schweigen oft", d: "Belastung zeigt sich bei Männern häufig anders: Gereiztheit, Rückzug, noch mehr Arbeit, mehr Alkohol. Auch das können Warnsignale für Erschöpfung oder Depression sein." } },

  // Achtsamkeit
  { t: "grid", title: "Achtsamkeit in den Wechseljahren", sub: "Was Studien und Leitlinien nahelegen",
    items: [["FaSpa", "Weniger Belastung", "Achtsamkeitstraining kann das Belastungserleben durch Hitzewallungen senken – auch wenn sie nicht seltener werden."],
      ["FaMoon", "Besserer Schlaf", "Teilnehmende berichten häufig über erholsameren Schlaf und weniger Grübeln."],
      ["FaSmile", "Stimmung", "Weniger Stress, Angst und Reizbarkeit, mehr Gelassenheit im Umgang mit dem Körper."]],
    notes: "Hintergrund: Studien zu MBSR in den Wechseljahren (u. a. Carmody et al., 2011) zeigten eine geringere Belastung durch Hitzewallungen sowie bessere Schlaf- und Lebensqualität. Kognitive Verhaltenstherapie wird in Leitlinien (z. B. NICE 2024) für Hitzewallungen und Stimmung empfohlen. Achtsamkeit ergänzt medizinische Behandlung, ersetzt sie aber nicht." },
  { t: "steps", title: "Die Hitzewelle surfen", pill: "ÜBUNG · 3 MIN",
    items: [["Bemerken", "„Da kommt eine Hitzewelle.“ Innerlich benennen, ohne Panik."],
      ["Nicht bekämpfen", "Schultern sinken lassen, Kiefer lockern."],
      ["Langsam atmen", "Vier Sekunden ein, sechs Sekunden aus – ruhig und gleichmäßig."],
      ["Beobachten", "Wo spüre ich die Hitze? Wie verändert sie sich?"],
      ["Abklingen lassen", "Die Welle erreicht einen Höhepunkt und ebbt ab. Bewusst nachspüren."]],
    side: { img: "32", icon: "FaWater", h: "Akzeptanz statt Kampf", d: "Eine Hitzewallung dauert meist nur wenige Minuten. Wer sie annimmt, erlebt sie oft als weniger bedrohlich." },
    notes: "Auch für Männer mit Stressreaktionen, Herzklopfen oder Schwitzen geeignet. Im Plenum einmal gemeinsam üben: Hitze in der Vorstellung entstehen lassen." },
  { t: "letters", title: "Selbstmitgefühl in drei Schritten", sub: "Nach Kristin Neff", pill: "ÜBUNG · 5 MIN",
    items: [["1", "Achtsamkeit", "„Das ist gerade schwer.“ Anerkennen, was ist – ohne zu dramatisieren."],
      ["2", "Verbundenheit", "„Viele Menschen in meinem Alter erleben das.“ Ich bin nicht allein."],
      ["3", "Freundlichkeit", "Eine Hand aufs Herz legen: „Was brauche ich jetzt?“ Mit mir sprechen wie mit einer guten Freundin."]],
    foot: "Selbstmitgefühl wirkt der Scham entgegen – und stärkt die Widerstandskraft." },
  { t: "grid", title: "Tipps für den Alltag", pill: "ALLTAGSTIPP",
    items: [["FaSnowflake", "Kühl schlafen", "Schlafzimmer um 16–18 °C, atmungsaktive Bettwäsche, Wasser ans Bett."],
      ["FaTshirt", "Zwiebellook", "Kleidung in Schichten, die sich schnell ablegen lässt."],
      ["FaDumbbell", "Bewegung", "Ausdauer und Krafttraining – gut für Stimmung, Schlaf, Knochen und Muskeln."],
      ["FaSearch", "Auslöser kennen", "Kaffee, Alkohol, scharfes Essen und Stress beobachten – ein Tagebuch hilft."],
      ["FaCarrot", "Ernährung", "Viel Gemüse, Vollkorn, Hülsenfrüchte; ausreichend trinken."],
      ["FaWind", "Atempausen", "Mehrmals täglich eine Minute bewusst und langsam atmen."]],
    notes: "Die Tipps gelten weitgehend auch für Männer – besonders Bewegung, Schlaf, Alkohol reduzieren und Stressbewältigung." },
  { t: "grid", title: "Was Arbeitgeber und Team tun können",
    items: [["FaComments", "Offenheit", "Das Thema enttabuisieren – Informationen, Vorträge, Gesprächsangebote."],
      ["FaFan", "Arbeitsplatz", "Tischventilator, Fenster, Temperatur regulieren, Wasser verfügbar."],
      ["FaClock", "Flexibilität", "Gleitzeit, Homeoffice, Pausen nach einer schlechten Nacht."],
      ["FaDoorClosed", "Rückzugsraum", "Ein ruhiger Ort für ein paar Minuten zum Durchatmen."],
      ["FaUserTie", "Führungskräfte", "Sensibilisieren und Gespräche wertschätzend führen."],
      ["FaHandsHelping", "Anlaufstellen", "Betriebliches Gesundheitsmanagement und Betriebsarzt einbinden."]],
    notes: "Gut ins Gespräch mit Personalrat, Gleichstellungsbeauftragter und BGM des Landkreises einbringen." },
  { t: "reflection", title: "Reflexion: Ich und diese Lebensphase", pill: "REFLEXION · 10 MIN",
    qs: ["Welche Veränderungen bemerke ich bei mir – körperlich, emotional, im Schlaf?", "Was hilft mir schon heute, gut mit Stress und Beschwerden umzugehen?",
      "Mit wem möchte ich offener darüber sprechen – privat oder beruflich?", "Wie kann ich Kolleginnen und Kollegen in dieser Phase unterstützen?"],
    notes: "Einzelreflexion. Austausch nur freiwillig und gern in selbst gewählten Kleingruppen – Rücksicht auf Scham und unterschiedliche Betroffenheit." },
  { t: "iconList", title: "Wann ärztlicher Rat wichtig ist",
    items: [["FaBed", "Starke Beschwerden", "Wenn Schlaf, Arbeit oder Beziehungen deutlich leiden."],
      ["FaCloudRain", "Anhaltende Niedergeschlagenheit", "Bei gedrückter Stimmung über Wochen, Hoffnungslosigkeit oder Ängsten."],
      ["FaVenus", "Frauen", "Bei ungewöhnlichen Blutungen, auch nach der Menopause, immer abklären lassen."],
      ["FaMars", "Männer", "Bei anhaltender Erschöpfung und Lustlosigkeit Ursachen und Testosteron prüfen lassen."]],
    side: { h: "Gut zu wissen", d: "Es gibt wirksame Behandlungen – von Hormontherapie über nicht-hormonelle Medikamente bis zur Verhaltenstherapie. Welche passt, entscheiden Sie gemeinsam mit Ihrer Ärztin oder Ihrem Arzt." },
    notes: "Ansprechpartner: gynäkologische, hausärztliche oder urologische Praxis; bei psychischer Belastung auch Psychotherapie. Hinweis auf die S3-Leitlinie „Peri- und Postmenopause“ der AWMF für Interessierte." },
];

(async () => {
  if (S.length !== 20) console.warn("WARN: slide count = " + S.length);
  const pres = await createDeck({ logo: path.join(__dirname, "logo_dark.png"), title: "Menopause, Stress und Achtsamkeit", slides: S, images: IMAGES, imageDir: path.join(__dirname, "bilder") });
  await pres.writeFile({ fileName: path.join(__dirname, "Zusatzmodul_Menopause_Stress_Achtsamkeit.pptx") });
  if (pres.missingImages.length) console.log("Platzhalter für Bilder:", pres.missingImages.join(", "));
  console.log("slides:", S.length);
})();
